# Generated by Django 4.0.3 on 2022-03-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Byte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('recipe', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks'), ('Snacks', 'Snacks')], max_length=50)),
                ('author', models.CharField(default='quick byte user', max_length=128)),
            ],
        ),
    ]
