# Generated by Django 4.0.3 on 2022-03-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbytes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byte',
            name='recipe',
            field=models.TextField(default='Remember it should be a short easy recipe with minimal ingredients...'),
        ),
    ]
